### ISSUE TITLE
Postgresql 12.3 连接数据库时报错

### ISSUE THREAD

**Issue by Hochikong** [databasefx/dbfx#2]
报错信息如下：
```
java.time.format.DateTimeParseException: Text 'infinity' could not be parsed at index 0
	at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2051)
	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1953)
	at java.base/java.time.OffsetDateTime.parse(OffsetDateTime.java:403)
	at io.vertx.pgclient.impl.codec.DataTypeCodec.textDecodeTIMESTAMPTZ(DataTypeCodec.java:1108)
	at io.vertx.pgclient.impl.codec.DataTypeCodec.decodeText(DataTypeCodec.java:539)
	at io.vertx.pgclient.impl.codec.RowResultDecoder.decodeRow(RowResultDecoder.java:47)
	at io.vertx.sqlclient.impl.RowDecoder.handleRow(RowDecoder.java:52)
	at io.vertx.pgclient.impl.codec.PgDecoder.decodeDataRow(PgDecoder.java:188)
	at io.vertx.pgclient.impl.codec.PgDecoder.channelRead(PgDecoder.java:90)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

我用于创建数据库用户的SQL如下：
```
CREATE ROLE ktmeta_test LOGIN PASSWORD 'ktmeta' VALID UNTIL 'infinity';

CREATE ROLE ktmeta INHERIT ;
GRANT ktmeta TO ktmeta_test ;
```

**Comment by GZYangKui** [comment]
一旦官方适配了pg指定值问题，这边立刻更新依赖。


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
